# Generated by Django 6.0.2 on 2026-02-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_file_alter_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='verification_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='verification_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='verification_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
