# Generated by Django 6.0.2 on 2026-02-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0002_add_smtp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='document_verification_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
